### PR TITLE
RX Gerbers Added

### PR DESCRIPTION
**Pull request by jlpoltrack**
Let me know if this works and I will do the Tx boards as well.

### CODE REVIEW

**Comment by olliw42** [comment]
oh wau ...

I'm not sure what I'm supposed to check to confirm that "it works"? :)

I have no idea what users would prefer, ziped or unzipped, but for me it all looks good

**Comment by jlpoltrack** [comment]
Was mostly asking if the folder structure was okay :). If so, I will create another 'gerbers' folder in the tx folder.

Zipped will be preferred.  If you want to try one out you can drag a .zip archive to an online gerber viewer (such as https://www.pcbway.com/project/OnlineGerberViewer.html) and see them rendered.

**Comment by olliw42** [comment]
cool, very cool
yes, could download a zip, drag and drop it, and see it :)
yes, folder structure looks great to me

**Comment by jlpoltrack** [comment]
Cool - added the Tx gerbers as well.

**Comment by olliw42** [comment]
fantastic
that's cool

**Pull request merged**
